name: whatsapp
description: A top package for whatsapp business api send messages, product, media, location through flutter app.
version: 4.0.0
homepage: https://rohitchouhan.com
repository: https://github.com/rohit-chouhan/whatsapp

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: "Â© WhatsApp"
    path: logo.png

topics:
  - whatsapp
  - whatsapp-business
  - whatsapp-api
  - wa
  - api
